# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 06:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tracking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check1', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=10, verbose_name='فرم ثبت نام')),
                ('check2', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=10, verbose_name='چک لیست مصاحبه')),
                ('check3', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=10, verbose_name='قرارداد امضا شده')),
                ('check4', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=10, verbose_name='کپی شناسنامه')),
                ('check5', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=10, verbose_name='کپی کارت ملی')),
                ('check6', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=10, verbose_name='سند اقامتگاه')),
                ('check7', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=10, verbose_name='گواهی سوء پیشینه')),
                ('check8', models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=10, verbose_name='تضمینات')),
            ],
            options={
                'verbose_name': 'مدارک',
                'verbose_name_plural': 'مدارک',
            },
        ),
        migrations.CreateModel(
            name='ConversationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_1', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح ۱')),
                ('detail_2', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح ۲')),
                ('detail_3', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح ۳')),
                ('detail_4', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح ۴')),
                ('detail_5', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح ۵')),
                ('detail_6', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح ۶')),
                ('detail_7', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح ۷')),
                ('detail_8', models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح ۸')),
                ('documentNum', models.CharField(max_length=50, verbose_name='شماره پرونده')),
                ('conversationDate', models.DateTimeField(verbose_name='تاریخ مصاحبه')),
                ('conversationNum', models.CharField(max_length=50, verbose_name='شماره مصاحبه')),
                ('rate_11', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='لباس مناسب و تمیز')),
                ('rate_12', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='توانایی جسمانی')),
                ('rate_13', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='فقدان علایم اعتیاد')),
                ('rate_14', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='فقدان خالکوبی و یقه باز')),
                ('rate_15', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='چهره و ظاهر قابل اعتماد ( زخم و غیره )')),
                ('rate_21', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='داشتن تلفن همراه')),
                ('rate_22', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='آشنایی با تلفن هوشمند (دیتا، آپدیت و غیره)')),
                ('rate_23', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='داشتن اکانت تلگرام')),
                ('rate_24', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='میزان آشنایی با اسنپ و تپسی')),
                ('rate_25', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='دریافت و درک درست از استادکار')),
                ('rate_31', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='میزان تبحر در رشته فعالیت خود')),
                ('rate_32', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='میزان آشنایی با علم روز کار')),
                ('rate_33', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='میزان آشنایی با ابزار ها')),
                ('rate_34', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='در اختیار داشتن ابزار های مورد نیاز')),
                ('rate_35', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='اطلاعات فرد در خصوص سایر خدمات')),
                ('rate_41', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='آرامش و اعتماد بنفس در صحبت')),
                ('rate_42', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='توانایی متقاعد سازی')),
                ('rate_43', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='خوب گوش دادن و صحبت به نوبت')),
                ('rate_44', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='توجه و تجزیه و تحلیل صحبت  ها')),
                ('rate_45', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='خوش رویی در هنگام مصاحبه')),
                ('rate_51', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='نظافت ناخن')),
                ('rate_52', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='بهداشت دهان و دندان')),
                ('rate_53', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='بهداشت و نظافت چهره ( استحمام )')),
                ('rate_54', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='مرتب و معقول و متعارف بودن مو و ریش')),
                ('rate_55', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='فقدان بوی نامطبوع بدن')),
                ('rate_61', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='نحوه سلام و احوال پرسی')),
                ('rate_62', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='استفاده از افعال و القاب مناسب')),
                ('rate_63', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='انتخاب سنجیده محتوای کلام')),
                ('rate_64', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='میزان صداقت در پاسخگویی')),
                ('rate_65', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='شفافیت در کلام و تعیین قیمت ( طفره نرفتن )')),
                ('rate_71', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='استفاده از لباس و کفش کار')),
                ('rate_72', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='میزان آشنایی با موارد ایمنی')),
                ('rate_73', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='میزان آشنایی با بیمه مسئولیت مدنی')),
                ('rate_74', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='میزان آشنایی یا قوانین صنفی')),
                ('rate_75', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='داشتن مجوز های ضروری')),
                ('rate_81', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='آرامش مقابل مخالفت و انتقاد پذیری')),
                ('rate_82', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='عکس العمل معقول')),
                ('rate_83', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='میزان انعطاف پذیری')),
                ('rate_84', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='فقدان تکبر یا تحکم در کلام')),
                ('rate_85', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='اعتماد وخوش بینی به استادکار')),
                ('moreDetails', models.CharField(max_length=1000, verbose_name='توضیح کلی')),
            ],
            options={
                'verbose_name': 'فرم شماره ۲',
                'verbose_name_plural': 'فرم شماره ۲',
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=200, unique=True, verbose_name='نام مصاحبه کننده')),
            ],
            options={
                'verbose_name': 'مصاحبه کننده',
                'verbose_name_plural': 'مصاحبه کنندگان',
                'ordering': ('interviewer',),
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='مهارت')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدرک',
                'ordering': ('expert',),
            },
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenterName', models.CharField(blank=True, default='', max_length=50, verbose_name='نام و نام خانوادگی معرف')),
                ('presenterJob', models.CharField(blank=True, default='', max_length=50, verbose_name='شغل معرف')),
                ('presenterAcademicLicence', models.CharField(blank=True, default='', max_length=50, verbose_name='تحصیلات معرف')),
                ('presenterRelation', models.CharField(blank=True, default='', max_length=50, verbose_name='نسبت آشنایی')),
                ('presenterTelephone', models.CharField(blank=True, default='', max_length=50, verbose_name='شماره تماس معرف')),
            ],
            options={
                'verbose_name': 'معرف',
                'verbose_name_plural': 'معرف ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True, verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ')),
                ('picture_0', models.ImageField(blank=True, null=True, upload_to=tracking.models.directory_path, verbose_name='تصویر همکار')),
                ('picture_11', models.ImageField(blank=True, null=True, upload_to=tracking.models.directory_path, verbose_name='تصویر روی کارت ملی')),
                ('picture_12', models.ImageField(blank=True, null=True, upload_to=tracking.models.directory_path, verbose_name='تصویر پشت کارت ملی')),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to=tracking.models.directory_path, verbose_name='تصویر شناسنامه')),
                ('provider_father_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام پدر')),
                ('national_code', models.CharField(blank=True, default='', max_length=10, verbose_name='کد ملی')),
                ('shenasname_code', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره شناسنامه')),
                ('born_city_1', models.CharField(blank=True, default='', max_length=100, verbose_name='محل تولد')),
                ('born_city_2', models.CharField(blank=True, default='', max_length=100, verbose_name='صادره از')),
                ('born_date', models.CharField(blank=True, default=' 1370/01/01', max_length=10, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], default='', max_length=10, verbose_name='جنسیت')),
                ('married', models.CharField(blank=True, choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل')], default='', max_length=10, verbose_name='وضعیت تاهل')),
                ('tell_phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره ثابت')),
                ('cell_phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='تلفن همراه برای نرم افزار')),
                ('academic_licence', models.CharField(blank=True, default='', max_length=50, verbose_name='مدرک تحصیلی')),
                ('credit_cart_number', models.CharField(blank=True, default='', max_length=16, verbose_name='شماره کارت بانکی')),
                ('bank_name', models.CharField(blank=True, default='', max_length=30, verbose_name='نام بانک')),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=30, verbose_name='شماره حساب بانکی')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='شهر')),
                ('region', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('3', '3'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], default='', max_length=10, verbose_name='منطقه شهری')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, verbose_name='کد پستی')),
            ],
            options={
                'verbose_name': 'فرم شماره ۱',
                'verbose_name_plural': 'فرم شماره ۱',
            },
        ),
        migrations.CreateModel(
            name='ProviderBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('cell_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='توجه: شماره تلفن ۱۱ رقمی است', regex='^.{11}$')], verbose_name='شماره تلفن همراه برای اپ')),
            ],
            options={
                'verbose_name': 'اطلاعات پایه همکار',
                'verbose_name_plural': 'اطلاعات پایه همکار',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectize', models.CharField(blank=True, choices=[('خوب', 'خوب'), ('متوسط', 'متوسط'), ('ضعیف', 'ضعیف')], max_length=100, verbose_name='مهارت')),
                ('work_experience', models.CharField(blank=True, max_length=100, verbose_name='سابقه کار')),
                ('explanation', models.CharField(blank=True, default='ندارد', max_length=500, verbose_name='توضیحات')),
                ('license', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='tracking.License', verbose_name='مدرک')),
                ('product_list', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Product', verbose_name='سرویس')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_skill', to='tracking.Provider')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='basic_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_basic_information', to='tracking.ProviderBasicInfo', verbose_name='اطلاعات پایه همکار'),
        ),
        migrations.AddField(
            model_name='provider',
            name='checkDocument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_check', to='tracking.CheckDocument', verbose_name='مدارک'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_presenter', to='tracking.Provider'),
        ),
        migrations.AddField(
            model_name='conversationdetail',
            name='interviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracking.Interviewer', verbose_name='مصاحبه کننده'),
        ),
        migrations.AddField(
            model_name='conversationdetail',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_ConversationDetail', to='tracking.Provider', verbose_name='همکار'),
        ),
    ]
