# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdocument',
            name='details',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='شرح همکاری'),
        ),
    ]
