# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_checkdocument_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkdocument',
            old_name='details',
            new_name='detail',
        ),
    ]
