# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_conversationdetail_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationdetail',
            name='basic_info',
        ),
        migrations.AddField(
            model_name='conversationdetail',
            name='information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracking.Provider', verbose_name='همکار'),
            preserve_default=False,
        ),
    ]
