# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20170519_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='basic_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic', to='tracking.ProviderBasicInfo', verbose_name='اطلاعات پایه همکار'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=tracking.models.directory_path, verbose_name='تصویر همکار'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to=tracking.models.directory_path, verbose_name='تصویر روی کارت ملی'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='picture_11',
            field=models.ImageField(blank=True, null=True, upload_to=tracking.models.directory_path, verbose_name='تصویر پشت کارت ملی'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to=tracking.models.directory_path, verbose_name='تصویر شناسنامه'),
        ),
    ]
